# Generated by Django 5.2.15 on 2026-06-23 18:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HardwareComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('CPU', 'Processor'), ('GPU', 'Graphics Card'), ('RAM', 'Memory'), ('MOBO', 'Motherboard'), ('PSU', 'Power Supply'), ('STORAGE', 'Storage')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('shop_link', models.URLField(blank=True, max_length=500, null=True)),
                ('specs', models.JSONField(blank=True, default=dict, help_text='Detalhes específicos como socket, TDP, vram, frequency, score (pontuação de benchmark).')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PCBuild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cpu', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='builds_as_cpu', to='hardware.hardwarecomponent')),
                ('gpu', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='builds_as_gpu', to='hardware.hardwarecomponent')),
                ('motherboard', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='builds_as_mobo', to='hardware.hardwarecomponent')),
                ('psu', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='builds_as_psu', to='hardware.hardwarecomponent')),
                ('ram', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='builds_as_ram', to='hardware.hardwarecomponent')),
                ('storage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='builds_as_storage', to='hardware.hardwarecomponent')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='builds', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
