# Generated by Django 5.2.15 on 2026-06-23 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('steam_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('cover_image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('genre', models.CharField(blank=True, max_length=100, null=True)),
                ('min_requirements', models.JSONField(blank=True, default=dict)),
                ('rec_requirements', models.JSONField(blank=True, default=dict)),
            ],
        ),
    ]
